import React from 'react';

export default function TermsOfService() {
    return (
        <div className="min-h-screen bg-neutral-950 text-neutral-200 py-20 px-6">
            <div className="max-w-3xl mx-auto glass-card p-8 md:p-12 rounded-2xl">
                <h1 className="text-3xl md:text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-teal-400 to-indigo-500 mb-8">
                    Terms of Service
                </h1>
                <p className="text-sm text-neutral-400 mb-8">Last Updated: February 24, 2026</p>

                <div className="space-y-8 text-neutral-300 leading-relaxed">
                    <section>
                        <h2 className="text-xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
                        <p>
                            By downloading, accessing, or using Lester Labs software or mobile applications (including &quot;Resume Refine&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use our services.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-4">2. Description of Service</h2>
                        <p>
                            Lester Labs provides artificial intelligence-powered tools designed to assist users in optimizing professional documents. &quot;Resume Refine&quot; processes public LinkedIn profiles and job descriptions via proprietary APIs and third-party Large Language Models (LLMs) to generate targeted resumes and cover letters.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-4">3. User Responsibilities & Acceptable Use</h2>
                        <p className="mb-4">
                            You agree to use our services only for lawful, professional purposes. You explicitly agree <strong>not</strong> to:
                        </p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Submit URLs or input text that contain abusive, defamatory, harassing, or discriminatory material.</li>
                            <li>Attempt to reverse-engineer, decompile, or extract the source code of the applications or our backend APIs.</li>
                            <li>Use the service to generate illegal or illicit content.</li>
                            <li>Overload or attempt to disrupt the performance of our servers.</li>
                        </ul>
                        <p className="mt-4">
                            We reserve the right to throttle, suspend, or terminate access for any user who violates these acceptable use policies.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-4">4. In-App Purchases and Consumables</h2>
                        <p>
                            Certain features within our applications may require a one-time In-App Purchase (Consumable) through Apple&apos;s App Store. Payments are charged to your Apple ID account at confirmation. Because the generative AI process executes immediately upon purchase, we do not offer direct refunds for completed generation requests. Any refund requests must be processed directly through Apple Support in accordance with their standard policies.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-4">5. Artificial Intelligence Disclaimer</h2>
                        <p>
                            Lester Labs utilizes advanced generative AI models. While we strive to produce high-quality, ATS-optimized content, AI responses can occasionally contain inaccuracies or hallucinations. <strong>You are solely responsible for reviewing, verifying, and editing all AI-generated content before utilizing it in any professional capacity or job application.</strong> Lester Labs assumes no liability for the outcomes of employment applications utilizing documents generated by our service.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-4">6. Third-Party Integrations</h2>
                        <p>
                            Our automated services interact with third-party platforms (such as LinkedIn) to retrieve public data requested by you. Lester Labs is not affiliated with, endorsed by, or sponsored by LinkedIn Corporation. We do not scrape non-public data or require your login credentials.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-4">7. Contact Us</h2>
                        <p>
                            For legal inquiries or support regarding these terms, please contact us at: <a href="mailto:nathan@lesterlabs.cloud" className="text-teal-400 hover:text-teal-300 transition-colors">support@lesterlabs.cloud</a>
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
}
